### ISSUE TITLE
KPM, MinutesPlayed, and WinRatio keys do not exist

### ISSUE THREAD

**Issue by LordKanelsnegle** [AeonLucid/FortniteApi#2]
Upon attempting to output any of the following code:
`response.Stats[Playlist.Solo][Stat.KillsPerMinute].Value`
`response.Stats[Playlist.Solo][Stat.MinutesPlayed].Value`
`response.Stats[Playlist.Solo][Stat.WinRatio].Value`
An exception is thrown that `response.Stats[Playlist.Solo]` does not contain the key provided.

**Comment by AeonLucid** [comment]
Fixed.

Those values are disabled at TRN because Fortnite does not return time played at the moment.
